### ISSUE TITLE
TODO list for 1.0.0

### ISSUE THREAD

**Issue by goneri** [ansible-collections/vmware.vmware_rest#46]
# Important
- [x] add functional test coverage for all the modules (https://github.com/ansible-collections/vmware_rest/issues/45)
- [ ] review the documentation (https://github.com/ansible-collections/vmware.vmware_rest/issues/102)
- [x] pass `ansible-test sanity`
    - [x] enable ansible-test-sanity-vmware-rest in Zuul https://github.com/ansible/ansible-zuul-jobs/pull/627
    - [x] deal with `filter.foo` (parameter-invalid) parameters https://github.com/ansible-collections/vmware_rest/issues/47
    - [x] defines type as list but elements is not defined (parameter-list-no-elements)
- [x] rename the repository (https://github.com/ansible-collections/vmware_rest/issues/18)
- [x] release `cloud.common` on Galaxy
- [ ] review the documentation of the modules
    - [ ] short description
- [x] Understand why we've got two different modules to handle the power managment of the guest: vcenter_vm_guest_power and vcenter_vm_power.
- [x] Correctly handle the case where the end-points don't expect a structure called "spec", but just a simple dict of key.
- [x] Properly pass environment variables to Ansible Module Turbo.

# communication
- [x] prepare an article to introduce the new collection (0.1.0)
- [ ] prepare another article to explain how to use the new collection (review in progress: https://github.com/ansible/ansible/pull/72090)

# Nice to have

- [x] expose more Ansible-ish `state` names, e.g: rename `state: create` to `state: present`
- [ ] give away to overwrite some sections of the documentation of a module. e.g: I'm fine with the auto-generated content, but I just want to clarify one parameter.
- [ ] give the users the ability to use a name+folder to identify a resource, like with community.vmware.
